apiVersion: apps/v1
kind: Deployment
metadata:
  name: payroll-deployment
  labels:
    app: payroll
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5003"
    prometheus.io/path: "/metrics"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payroll
  template:
    metadata:
      labels:
        app: payroll
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5003"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: payroll
        image: nourgharby/teamflow-payroll:1.0
        imagePullPolicy: Always

        ports:
        - containerPort: 5003

        readinessProbe:
          httpGet:
            path: /healthz
            port: 5003
          initialDelaySeconds: 5
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /healthz
            port: 5003
          initialDelaySeconds: 10
          periodSeconds: 15

---
apiVersion: v1
kind: Service
metadata:
  name: payroll-service
  labels:
    app: payroll
spec:
  selector:
    app: payroll
  ports:
  - port: 80
    targetPort: 5003
